version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
    commit-message:
      prefix: 'ci'
    labels:
      - 'Scope: Dependencies'
      - 'Type: Maintenance'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: 'auto'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
    commit-message:
      prefix: 'ci'
    labels:
      - 'Scope: Dependencies'
      - 'Type: Maintenance'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: 'auto'
    groups:
      npm-deps:
        update-types: [minor, patch]
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
