export const preset = 'ts-jest'
export const testEnvironment = 'node'
export const roots = ['<rootDir>/tests']
export const testMatch = ['**/*.test.ts']
export const collectCoverageFrom = ['src/**/*.ts', '!src/**/*.d.ts']
export const coverageDirectory = 'coverage'
export const coverageReporters = ['text', 'lcov', 'html']
export const forceExit = true
export const clearMocks = true
export const testTimeout = 30000
export const detectOpenHandles = false
